CREATE DATABASE dostaevskiy;
USE dostaevskiy;
SHOW TABLES;

-- Создание таблиц

CREATE TABLE catalogs (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT 'Разделы меню';


CREATE TABLE menu (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
catalog_id INT UNSIGNED NOT NULL COMMENT 'Ссылка на размел меню',
name VARCHAR(50) NOT NULL UNIQUE,
description VARCHAR(255) NOT NULL,
photo VARCHAR(255) NOT NULL COMMENT 'Ссылка на файл',
price INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT menu_catalog_id_fk 
	FOREIGN KEY (catalog_id) REFERENCES catalogs (id) ON DELETE CASCADE,
INDEX(name, price)
) COMMENT 'Меню';


CREATE TABLE address (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (255),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT 'Адреса клиентов';


CREATE TABLE users (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
phone VARCHAR(100) NOT NULL UNIQUE,
address_id INT UNSIGNED,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT users_address_id_fk 
	FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE SET NULL,
INDEX (name)
) COMMENT 'Клиенты';


CREATE TABLE delivery_area (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT 'Зоны доставки';


CREATE TABLE discounts (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
catalog_id INT UNSIGNED NOT NULL,
discount FLOAT UNSIGNED,
started_at TIME,
finished_at TIME,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT discounts_user_id_fk 
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
CONSTRAINT discounts_catalod_id_fk
	FOREIGN KEY (catalog_id) REFERENCES catalogs (id) ON DELETE CASCADE
) COMMENT 'Скидки';


CREATE TABLE payments (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (100),
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT 'Споособы оплаты';

CREATE TABLE orders (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id INT UNSIGNED NOT NULL,
menu_id INT UNSIGNED NOT NULL,
total INT UNSIGNED DEFAULT 1 COMMENT 'Количество заказанных товарных позиций',
address_id INT UNSIGNED NOT NULL,
payment_id INT UNSIGNED NOT NULL COMMENT 'Способ оплаты',
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
deliver_before DATETIME DEFAULT (CURRENT_TIMESTAMP + INTERVAL 1 HOUR),
delivery_at DATETIME DEFAULT (CURRENT_TIMESTAMP + INTERVAL 1 HOUR),
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT orders_user_id_fk 
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION,
CONSTRAINT orders_menu_id_fk 
	FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE RESTRICT,
CONSTRAINT orders_address_id_fk
	FOREIGN KEY (address_id) REFERENCES address (id) ON DELETE RESTRICT,
CONSTRAINT orders_payment_id_fk
	FOREIGN KEY (payment_id) REFERENCES payments (id) ON DELETE RESTRICT
) COMMENT 'Заказы';

ALTER TABLE orders ADD COLUMN delivery_at DATETIME DEFAULT (CURRENT_TIMESTAMP + INTERVAL 1 HOUR) AFTER  deliver_before;

CREATE TABLE couriers (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
phone VARCHAR(50) NOT NULL UNIQUE,
delivery_area_id INT UNSIGNED NOT NULL DEFAULT 1,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT couriers_delivery_area_id_fk 
	FOREIGN KEY (delivery_area_id) REFERENCES delivery_area (id) ON DELETE SET DEFAULT
) COMMENT 'Курьеры';


CREATE TABLE order_statuses (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT 'Статусы заказов';


CREATE TABLE orders_couriers (
order_id INT UNSIGNED NOT NULL,
courier_id INT UNSIGNED NOT NULL,
order_status_id INT UNSIGNED NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (order_id, courier_id),
CONSTRAINT orders_couriers_order_status_id_fk
	FOREIGN KEY (order_status_id) REFERENCES order_statuses (id) ON DELETE NO ACTION,
CONSTRAINT orders_couriers_order_id_fk
	FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
CONSTRAINT orders_couriers_courier_id_fk
	FOREIGN KEY (courier_id) REFERENCES couriers (id) ON DELETE CASCADE
) COMMENT 'Заказы в работе';


CREATE TABLE orders_comments (
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
order_id INT UNSIGNED NOT NULL,
description VARCHAR(255),
grade TINYINT UNSIGNED,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
update_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT orders_comments_order_id_fk
	FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE,
INDEX (grade)
) COMMENT 'Оценка заказов';




